server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:123456@localhost:${server.port}/eureka/

spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: 123456
  cloud:
    config:
      enabled: false
